shoulder_yaw_offset: 0
shoulder_pitch_offset: 0
forearm_pitch_offset: 0
wrist_pitch_offset: 0
wrist_yaw_offset: 0
shoulder_yaw_scaling: 1
shoulder_pitch_scaling: 1
forearm_pitch_scaling: 1
wrist_pitch_scaling: 1
wrist_yaw_scaling: 1
