shoulder_yaw_offset:
    initial_value: 65322
    lower_limit: 0
    upper_limit: 100000
shoulder_pitch_offset:
    initial_value: 3792
    lower_limit: 0
    upper_limit: 100000
forearm_pitch_offset:
    initial_value: 59777
    lower_limit: 0
    upper_limit: 100000
wrist_pitch_offset:
    initial_value: 64437
    lower_limit: 0
    upper_limit: 100000
wrist_yaw_offset:
    initial_value: 65252
    lower_limit: 0
    upper_limit: 100000

shoulder_yaw_scaling:
    initial_value: 1
    lower_limit: 0
    upper_limit: 100
shoulder_pitch_scaling:
    initial_value: 1
    lower_limit: 0
    upper_limit: 100
forearm_pitch_scaling:
    initial_value: 1
    lower_limit: 0
    upper_limit: 100
wrist_pitch_scaling:
    initial_value: 1
    lower_limit: 0
    upper_limit: 100
wrist_yaw_scaling:
    initial_value: 1
    lower_limit: 0
    upper_limit: 100
