shoulder_yaw_offset:
    initial_value: 66322
    lower_limit: 0
    upper_limit: 100000
    uncertainty: 100
shoulder_pitch_offset:
    initial_value: 3692
    lower_limit: 0
    upper_limit: 100000
    uncertainty: 100
forearm_pitch_offset:
    initial_value: 60777
    lower_limit: 0
    upper_limit: 100000
    uncertainty: 100
wrist_pitch_offset:
    initial_value: 63437
    lower_limit: 0
    upper_limit: 100000
    uncertainty: 100
wrist_yaw_offset:
    initial_value: 66324
    lower_limit: 0
    upper_limit: 100000
    uncertainty: 100

shoulder_yaw_scaling:
    initial_value: 47
    lower_limit: 0
    upper_limit: 100
    uncertainty: 1
shoulder_pitch_scaling:
    initial_value: 50
    lower_limit: 0
    upper_limit: 100
    uncertainty: 1
forearm_pitch_scaling:
    initial_value: 51
    lower_limit: 0
    upper_limit: 100
    uncertainty: 1
wrist_pitch_scaling:
    initial_value: 47
    lower_limit: 0
    upper_limit: 100
    uncertainty: 1
wrist_yaw_scaling:
    initial_value: 47
    lower_limit: 0
    upper_limit: 100
    uncertainty: 1
