shoulder_yaw_offset: 0.325
shoulder_pitch_offset: 0.325643
forearm_pitch_offset: 0.325643
wrist_pitch_offset: 0.325643
wrist_yaw_offset: 0.325643
wrist_rotate_offset: 0.325643
shoulder_yaw_scaling: 0.325643
shoulder_pitch_scaling: 0.325643
forearm_pitch_scaling: 0.325643
wrist_pitch_scaling: 0.325643
wrist_yaw_scaling: 0.325643
wrist_rotate_scaling: 0.325643
fisheye_mount_x_correction: 253
fisheye_mount_y_correction: 15
fisheye_mount_z_correction: 4.7
fisheye_mount_a_correction: 4.6
fisheye_mount_b_correction: 87
fisheye_mount_c_correction: 45
