shoulder_yaw_offset: 0.325
shoulder_pitch_offset: 0.325643
forearm_pitch_offset: 0.325643
wrist_pitch_offset: 0.325643
wrist_yaw_offset: 0.325643
wrist_rotate_offset: 0.325643
shoulder_yaw_scaling: 0.325643
shoulder_pitch_scaling: 0.325643
forearm_pitch_scaling: 0.325643
wrist_pitch_scaling: 0.325643
wrist_yaw_scaling: 0.325643
wrist_rotate_scaling: 0.325643
fisheye_mount_x: 253
fisheye_mount_y: 15
fisheye_mount_z: 4.7
fisheye_mount_a: 4.6
fisheye_mount_b: 87
fisheye_mount_c: 45
