# Service request

FreeParameters free_params
OptimizationParameters opt_params
CalibrationData data
std_msgs/String robot_description
---
# Service response

float64 starting_variance
float64 ending_variance
FreeParameters params
